# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: efdd73b73f77d5b090a02077679d0bf1808b72b5e469fa442908c666f17fac4b18596a5e08da26b3f757e583b439ace716a66f7aa1723a21dc7f08fdc4dd742a

test:
  secret_key_base: 6bee6208697683f9e2a66342c379f231103c8d0c4123db6adc33d269a0944a2bc69953606afb259a434e8d4e4f65512bfc48b15236609db77b7fc99bfa22cb17

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 83fe4316d6b3649430eef0db39ed470e8e0f2fb0e86a74d5732cedba3f11c2005b9af2566a5e55814e329803855f9dcb4496f0ef12ec7cc49f2af002b3c1e2cd

